/**
 * i18n setup for vue-i18n
 *
 * Translation files are generated by the `fetch-translations` script from the
 * Google Spreadsheet: https://docs.google.com/spreadsheets/d/1m3TlNDa8J6bbXcbgqTOcH-UZdtxtqYJay3auj_xHA7g
 *
 * Format produced by @el-j/google-sheet-translations:
 *   { "i18n": { "section.key": "value", ... }, "landingPage": { "key": "value", ... } }
 *
 * This module flattens those dot-notation keys into nested objects for vue-i18n.
 */

import { createI18n } from 'vue-i18n'
import enRaw from './translations/en.json'

/** A single sheet's key→value map as written by @el-j/google-sheet-translations. */
type SheetMap = Record<string, string>

/** The raw JSON shape: one object per sheet tab keyed by tab name. */
type RawLocaleFile = Record<string, SheetMap>

/** Nested message object after dot-key expansion, suitable for vue-i18n. */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface MessageTree extends Record<string, string | MessageTree> {}

/**
 * Eagerly-imported locale modules.
 * Add entries here when new locale files are generated by fetch-translations.
 */
const localeModules: Record<string, RawLocaleFile> = {
  en: enRaw as RawLocaleFile,
}

// Attempt to import generated locale files (gracefully absent on first run)
try {
  const deRaw = await import('./translations/de.json').catch(() => null)
  if (deRaw) localeModules['de'] = (deRaw.default ?? deRaw) as RawLocaleFile
} catch { /* locale not yet generated */ }

try {
  const frRaw = await import('./translations/fr.json').catch(() => null)
  if (frRaw) localeModules['fr'] = (frRaw.default ?? frRaw) as RawLocaleFile
} catch { /* locale not yet generated */ }

try {
  const esRaw = await import('./translations/es.json').catch(() => null)
  if (esRaw) localeModules['es'] = (esRaw.default ?? esRaw) as RawLocaleFile
} catch { /* locale not yet generated */ }

/**
 * Expands flat dot-notation keys into a nested object.
 * e.g. { "nav.services": "Services" } → { nav: { services: "Services" } }
 */
function expandDotKeys(flat: SheetMap): MessageTree {
  const result: MessageTree = {}
  for (const [dotKey, value] of Object.entries(flat)) {
    const parts = dotKey.split('.')
    let cursor: MessageTree = result
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i]
      const existing = cursor[part]
      cursor[part] = existing && typeof existing === 'object' && !Array.isArray(existing) ? existing : {}
      cursor = cursor[part] as MessageTree
    }
    cursor[parts[parts.length - 1]] = value
  }
  return result
}

/**
 * Normalises a raw translation file into vue-i18n message format.
 *
 * The @el-j/google-sheet-translations package writes one key per sheet tab:
 *   { "i18n": { "nav.services": "Services", ... }, "landingPage": { "hero.badge": "…", ... } }
 *
 * Merge all sheet objects into one flat map, then expand dot-notation to nested objects.
 */
function normalise(raw: RawLocaleFile): MessageTree {
  const data: RawLocaleFile = (raw as { default?: RawLocaleFile }).default ?? raw
  const flat: SheetMap = Object.values(data).reduce<SheetMap>((acc, sheet) => {
    if (sheet && typeof sheet === 'object' && !Array.isArray(sheet)) {
      Object.assign(acc, sheet)
    }
    return acc
  }, {})
  return expandDotKeys(flat)
}

/**
 * Returns true when a locale has at least one translated key.
 * Prevents empty placeholder files (generated before fetch-translations ran)
 * from appearing in the language switcher with no content.
 */
function hasTranslations(msgs: MessageTree): boolean {
  return Object.keys(msgs).length > 0
}

// Build vue-i18n messages map
const messages: Record<string, MessageTree> = {}
for (const [locale, raw] of Object.entries(localeModules)) {
  messages[locale] = normalise(raw)
}

/**
 * Sorted list of locale codes that actually have content.
 * 'en' is always included (it is the source locale).
 * Other locales are only included when the generated translation file contains
 * at least one key, i.e. after `npm run fetch-translations` has been run.
 */
export const availableLocales: string[] = Object.keys(messages)
  .filter(locale => locale === 'en' || hasTranslations(messages[locale]))
  .sort()

/** Default locale — prefer browser language, fall back to English */
function detectLocale(): string {
  if (typeof navigator === 'undefined') return 'en'
  const lang = navigator.language?.slice(0, 2).toLowerCase()
  return availableLocales.includes(lang) ? lang : 'en'
}

const i18n = createI18n({
  legacy: false,          // Composition API mode
  locale: detectLocale(),
  fallbackLocale: 'en',
  messages,
  missingWarn: false,
  fallbackWarn: false,
})

export default i18n
