/**
 * i18n setup for vue-i18n
 *
 * Translation files are generated by the `fetch-translations` script from the
 * Google Spreadsheet: https://docs.google.com/spreadsheets/d/1m3TlNDa8J6bbXcbgqTOcH-UZdtxtqYJay3auj_xHA7g
 *
 * Format produced by @el-j/google-sheet-translations:
 *   { "i18n": { "section.key": "value", ... } }
 *
 * This module flattens those dot-notation keys into nested objects for vue-i18n.
 */

import { createI18n } from 'vue-i18n'
import enRaw from './translations/en.json'

/**
 * Eagerly-imported locale modules.
 * Add entries here when new locale files are generated by fetch-translations.
 */
const localeModules = {
  en: enRaw,
}

// Attempt to import generated locale files (gracefully absent on first run)
try {
  const deRaw = await import('./translations/de.json').catch(() => null)
  if (deRaw) localeModules.de = deRaw.default ?? deRaw
} catch { /* locale not yet generated */ }

try {
  const frRaw = await import('./translations/fr.json').catch(() => null)
  if (frRaw) localeModules.fr = frRaw.default ?? frRaw
} catch { /* locale not yet generated */ }

try {
  const esRaw = await import('./translations/es.json').catch(() => null)
  if (esRaw) localeModules.es = esRaw.default ?? esRaw
} catch { /* locale not yet generated */ }

/**
 * Expands flat dot-notation keys into a nested object.
 * e.g. { "nav.services": "Services" } → { nav: { services: "Services" } }
 */
function expandDotKeys(flat) {
  const result = {}
  for (const [dotKey, value] of Object.entries(flat)) {
    const parts = dotKey.split('.')
    let cursor = result
    for (let i = 0; i < parts.length - 1; i++) {
      const part = parts[i]
      cursor[part] = cursor[part] && typeof cursor[part] === 'object' && !Array.isArray(cursor[part]) ? cursor[part] : {}
      cursor = cursor[part]
    }
    cursor[parts[parts.length - 1]] = value
  }
  return result
}

/**
 * Normalises a raw translation file into vue-i18n message format.
 *
 * The @el-j/google-sheet-translations package writes one key per sheet tab:
 *   { "i18n": { "nav.services": "Services", ... }, "landingPage": { "hero.badge": "…", ... } }
 *
 * Merge all sheet objects into one flat map, then expand dot-notation to nested objects.
 */
function normalise(raw) {
  const data = raw.default ?? raw
  const flat = Object.values(data).reduce((acc, sheet) => {
    if (sheet && typeof sheet === 'object' && !Array.isArray(sheet)) {
      Object.assign(acc, sheet)
    }
    return acc
  }, {})
  return expandDotKeys(flat)
}

// Build vue-i18n messages map
const messages = {}
for (const [locale, raw] of Object.entries(localeModules)) {
  messages[locale] = normalise(raw)
}

/** Sorted list of available locale codes (e.g. ['de','en','fr']) */
export const availableLocales = Object.keys(messages).sort()

/** Default locale — prefer browser language, fall back to English */
function detectLocale() {
  if (typeof navigator === 'undefined') return 'en'
  const lang = navigator.language?.slice(0, 2).toLowerCase()
  return availableLocales.includes(lang) ? lang : 'en'
}

const i18n = createI18n({
  legacy: false,          // Composition API mode
  locale: detectLocale(),
  fallbackLocale: 'en',
  messages,
  missingWarn: false,
  fallbackWarn: false,
})

export default i18n
